### ISSUE TITLE
Substitute “button looking” badges with plain text labels

### ISSUE THREAD

**Issue by ekate** [nyudlts/ultraviolet#59]
Substitute “button looking” badges with plain text labels

**Comment by lhenze** [comment]
Here's the mockup for the metadata displayed as plain text, rather than looking like badges or tags.
<img width="703" alt="metadata-as-plain-text" src="https://user-images.githubusercontent.com/86330/135337146-e2fae46f-8e61-43f1-8378-1fc6322dd4f5.png">

**Comment by mnyrop** [comment]
notes to self (wip):
```scss
.ui.items > .item .extra {
    color: #444;
    text-transform: uppercase;
    font-weight: 600;
}
```
